export const themes = {
  default: {
    id: 'default',
    name: 'Default',
    appBg: 'bg-gradient-to-br from-indigo-50 via-white to-purple-50',
    navBg: 'bg-white/70',
    textMain: 'text-gray-900',
    textMuted: 'text-gray-500',
    cardBg: 'bg-white',
    border: 'border-gray-200/50',
    cardBorder: 'border-gray-100',
    primaryText: 'text-indigo-600',
    primaryBg: 'bg-indigo-600',
    primaryBgHover: 'hover:bg-indigo-700',
    logoGradient: 'from-indigo-600 to-purple-600',
    tableHeader: 'bg-gray-50',
    inputBorder: 'border-gray-300',
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    appBg: 'bg-slate-900',
    navBg: 'bg-slate-800/80',
    textMain: 'text-slate-50',
    textMuted: 'text-slate-400',
    cardBg: 'bg-slate-800',
    border: 'border-slate-700/50',
    cardBorder: 'border-slate-700',
    primaryText: 'text-cyan-400',
    primaryBg: 'bg-cyan-500',
    primaryBgHover: 'hover:bg-cyan-600',
    logoGradient: 'from-cyan-400 to-fuchsia-500',
    tableHeader: 'bg-slate-700',
    inputBorder: 'border-slate-600',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    appBg: 'bg-gradient-to-br from-rose-50 via-orange-50 to-amber-50',
    navBg: 'bg-white/70',
    textMain: 'text-stone-900',
    textMuted: 'text-stone-500',
    cardBg: 'bg-white',
    border: 'border-stone-200/50',
    cardBorder: 'border-stone-100',
    primaryText: 'text-rose-600',
    primaryBg: 'bg-rose-600',
    primaryBgHover: 'hover:bg-rose-700',
    logoGradient: 'from-rose-600 to-orange-500',
    tableHeader: 'bg-stone-50',
    inputBorder: 'border-stone-300',
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    appBg: 'bg-gradient-to-br from-blue-50 to-teal-50',
    navBg: 'bg-white/70',
    textMain: 'text-slate-900',
    textMuted: 'text-slate-500',
    cardBg: 'bg-white',
    border: 'border-slate-200/50',
    cardBorder: 'border-slate-100',
    primaryText: 'text-blue-700',
    primaryBg: 'bg-blue-600',
    primaryBgHover: 'hover:bg-blue-700',
    logoGradient: 'from-blue-700 to-teal-500',
    tableHeader: 'bg-slate-50',
    inputBorder: 'border-slate-300',
  },
  earth: {
    id: 'earth',
    name: 'Earth',
    appBg: 'bg-stone-100',
    navBg: 'bg-stone-50/80',
    textMain: 'text-stone-800',
    textMuted: 'text-stone-500',
    cardBg: 'bg-stone-50',
    border: 'border-stone-200/50',
    cardBorder: 'border-stone-200',
    primaryText: 'text-emerald-700',
    primaryBg: 'bg-emerald-600',
    primaryBgHover: 'hover:bg-emerald-700',
    logoGradient: 'from-emerald-700 to-lime-600',
    tableHeader: 'bg-stone-100',
    inputBorder: 'border-stone-300',
  }
};
